openapi: 3.0.0
info:
  description: Basic API for retrieving schedules, based on a ScheduleInput object.
  title: Scheduler API
  version: 0.0.1
servers:
- url: http://localhost:8080
paths:
  /schedule:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
          description: A schedule.
      summary: Returns a generated schedule.
  /model-parameters/get:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelParameters'
          description: Succesful operation.
      summary: Returns the current model parameters.
  /model-parameters/set:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModelParameters'
        description: The model parameters to be set.
        required: true
      responses:
        "204":
          description: Model parameters succesfully updated in backend.
      summary: Sets the model paramters in the backend.
  /instance-data/get:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstanceData'
          description: Succesful operation.
      summary: Returns the current instance data.
  /instance-data/set:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstanceData'
        description: The instance data to be set.
        required: true
      responses:
        "204":
          description: Instance data succesfully updated in backend.
      summary: Sets the insatnce data in the backend.
components:
  schemas:
    Schedule:
      description: Holds all data of a generated schedule.
      example:
        nb_days: 1
        individual_schedules:
        - assistant_id: 2
          assignments:
          - part_of_min_balance: true
          - part_of_min_balance: true
        - assistant_id: 2
          assignments:
          - part_of_min_balance: true
          - part_of_min_balance: true
        assistants:
        - workload: 5.637376656633329
          id: 5
        - workload: 5.637376656633329
          id: 5
        fairness_score: 0.8008281904610115
        balance_score: 6
        shift_types:
        - null
        - null
      properties:
        fairness_score:
          description: The fairness score of this schedule
          type: number
        balance_score:
          description: The balance score of this schedule
          type: integer
        nb_days:
          description: The number of days for which this schedule is generated.
          type: integer
        assistants:
          description: The assistants involved in this schedule.
          items:
            $ref: '#/components/schemas/Assistant'
          type: array
        shift_types:
          description: The shift types that were considered when generating this schedule.
          items:
            $ref: '#/components/schemas/ShiftType'
          type: array
        individual_schedules:
          items:
            $ref: '#/components/schemas/IndividualSchedule'
          type: array
      type: object
    Assistant:
      description: Represents an assistant.
      example:
        workload: 5.637376656633329
        id: 5
      properties:
        id:
          description: The identification number of this assistant.
          type: integer
        type:
          $ref: '#/components/schemas/AssistantType'
        workload:
          description: The workload on this assiastant in the schedule.
          type: number
      required:
      - id
      - type
      type: object
    IndividualSchedule:
      description: Represents the work schedule of an individual assistant.
      example:
        assistant_id: 2
        assignments:
        - part_of_min_balance: true
        - part_of_min_balance: true
      properties:
        assistant_id:
          description: The identification number of the assistant for which this is
            an individual schedule.
          type: integer
        assignments:
          description: An array as long as the number of days of this schedule. Contains
            all the assignments that have been scheduled to this assistant.
          items:
            $ref: '#/components/schemas/Assignment'
          type: array
      type: object
    Assignment:
      description: Represents a single shift assignment.
      example:
        part_of_min_balance: true
      properties:
        shift_type:
          $ref: '#/components/schemas/ShiftType'
        part_of_min_balance:
          description: whether or not this assignment is part of a min balance free
            block.
          type: boolean
      required:
      - part_of_min_balance
      - shift_type
      type: object
    AssistantType:
      description: The different assistant types.
      enum:
      - JA
      - JA_F
      - SA
      - SA_F
      - SA_NEO
      - SA_F_NEO
      type: string
    ShiftType:
      description: The different shift types that can be scheduled, including the
        free shift.
      enum:
      - JAEV
      - JAWH
      - JANW
      - SAEW
      - SAWH
      - TSPT
      - CALL
      - FREE
      type: string
    ModelParameters:
      description: Holds all model parameters to generate a schedule.
      example:
        balance_minimun_jaev: 6
        balance_minimum: 0
        shift_type_params:
        - max_buffer: 5
          shift_workload: 1.4658129805029452
        - max_buffer: 5
          shift_workload: 1.4658129805029452
      properties:
        balance_minimum:
          description: The minimal balance score for an acceptable solution.
          type: integer
        balance_minimun_jaev:
          description: The mininmal balance score for JAEV shifts for an acceptable
            solution.
          type: integer
        shift_type_params:
          items:
            $ref: '#/components/schemas/ShiftTypeModelParameters'
          type: array
      type: object
    ShiftTypeModelParameters:
      description: Holds the shift type specific model parameters.
      example:
        max_buffer: 5
        shift_workload: 1.4658129805029452
      properties:
        shift_type:
          $ref: '#/components/schemas/ShiftType'
        shift_workload:
          description: The weight of this shift type in the fairness score.
          type: number
        max_buffer:
          description: The number of assignments per assisant allowed above the minimun
            for this shift type.
          type: integer
      required:
      - max_buffer
      - shift_type
      - shift_workload
      type: object
    InstanceData:
      description: Holds the instance data for scheduling.
      example:
        assistants:
        - id: 0
        - id: 0
        nb_weeks: 6
      properties:
        assistants:
          items:
            $ref: '#/components/schemas/AssistantInstance'
          type: array
        nb_weeks:
          description: The number of weeks to be scheduled in this instance
          type: integer
      type: object
    AssistantInstance:
      description: Holds all instance data for one assistant.
      example:
        id: 0
      properties:
        id:
          description: The identification number of this assistant.
          type: integer
        type:
          $ref: '#/components/schemas/AssistantType'
      type: object
